name: build-check
on:
    # push:
    #     branches: ["v2", "main"]
    pull_request:
        branches: ["v2", "main"]

permissions:
    contents: read
    pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: "${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: yarn
            - run: yarn
            - run: yarn format:check

    front-end-build:
        strategy:
            # fail-fast: false
            matrix:
                os: [windows, ubuntu]
                node-version: [16, latest]
        runs-on: ${{ matrix.os }}-latest
        timeout-minutes: 8
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  cache: yarn
                  node-version: ${{ matrix.node-version }}

            - run: yarn

            - run: yarn manifest
            - run: yarn stickers
            - run: yarn client:build
            - run: yarn website:build

            - uses: actions/upload-artifact@v3
              with:
                  name: FE-${{ matrix.os }}-${{ matrix.node-version }}
                  path: |
                      website/build/
                      client-config-app/build/
                      manifest/build/
                      official-stickers/build/
                  retention-days: 5

    back-end-build:
        strategy:
            # fail-fast: false
            matrix:
                os: [windows, ubuntu]
                dotnet-version: [6.x]
        runs-on: ${{ matrix.os }}-latest
        timeout-minutes: 8
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: ${{ matrix.dotnet-version }}

            - run: dotnet build server.net -c Release
            - run: dotnet build image-functions -c Release
